version: '3'
services:
  server:
    image: rancher/k3s:v0.6.1
    command: server --disable-agent --no-deploy=traefik --no-deploy=servicelb 
    #--kube-apiserver-arg service-cluster-ip-range=100.64.0.0/16
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    - ./manifests:/var/lib/rancher/k3s/server/manifests
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v0.6.1
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c
    expose:
    - "31380"
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'

volumes:
  k3s-server: {}
