apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1RENDQWN5Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFqTVJBd0RnWURWUVFLRXdkck0zTXQKYjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd0hoY05NVGt3TnpFMU1UUXhOVFUzV2hjTk1qa3dOekV5TVRReApOVFUzV2pBak1SQXdEZ1lEVlFRS0V3ZHJNM010YjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQXY3cE93cFYzTm9ibTh1YnJQYjlmRVd2REpIaEUKYjBmaWYvbGw4TitmUURjNk01ZFpDL1ZUUnFEU3pMVzlDanNGVHkxbm5Fc05EL0UyL3ZVVEZRdEg4ZkhocFoydQo2R05GSlNsYlJBeHZlWmFkbmVRQ2lrTnpvdW5NaUZGaWZPQzVjUjgvYXN5Y3FReUZUbldVQ1VuZkZsa0hhL214Cnc1VGQ2MGJaNUkvcWtneVhEZ0ZlMWZ4UTRWV0dhRXloenZmV2NJTzcraDlKZWtoaVN1YVpGVzJMUVQzWFROSkwKbHZjTGdzTjJ5b2NWNGVXTEZWd0VxUmNHbWRnZzVkOC9hVk5WYmptU1dRMjBjOFZrc21sWk9nL2FvRFNvczRHNwpwUjJpNUZ0QzlDelJLQVBFYzRleThBdjFhN3ErNzB4V1Y2MUE2NkNkSXN3SzRvaTNpMnBPT3R5ZEFnTUJBQUdqCkl6QWhNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUFjdFZIYUxIYjFnMldGczlRY0Q4WnJHZWxoUm1JUC9GaEtORnRjR0xGU0o0SnVwQ25ibjJydwpjMWRndTNwVWUrWHl3dGlmbnpsNTd4OFdJTnZ3K2gxZGhSODUvcUtaSXV6SDlCZVZRUlZ5S01aY3UzRExEdGkyCk9QanZRRXJXR3Z3Z0J4Mm51YWtJUFhaem9iMkZlMEJkZ1VHTURYcUlVNUViRGx5SkRwK2tPQnlnNTM4UEJQMCsKZksxWXJjMS8yQVVMenJrZ25zNHZWREVaMWNCc0xnVzFMcFo5UWdLWTdNaVlmKzNFQkJlbUROdWtIUFZNR1p2SQorOWVVRmEzTDVaUXEyRGVNemQ2dklDNHptN3dVQzRCY0lQM1hDTFp3a0ZDSC9raUpEVStEREdUdjV2dW10RE9kCjBpcmhvVldzdCtQaGc4czd6VFQyV3lsSjFaazRmdmhNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://localhost:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: dc869240eb4f15b22be9033af7069164
    username: admin
